-- Execute conectado no banco alvo (ex.: flowpay local ou postgres no Supabase).

CREATE TABLE IF NOT EXISTS atendentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    time_atendimento VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT,
    CONSTRAINT chk_atendente_time
        CHECK (time_atendimento IN ('CARTOES', 'EMPRESTIMOS', 'OUTROS_ASSUNTOS'))
);

CREATE TABLE IF NOT EXISTS atendimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(120) NOT NULL,
    documento_cliente VARCHAR(30) NOT NULL,
    assunto VARCHAR(40) NOT NULL,
    time_atendimento VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    atendente_id BIGINT,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
    iniciado_em TIMESTAMP,
    finalizado_em TIMESTAMP,
    version BIGINT,
    CONSTRAINT fk_atendimentos_atendente
        FOREIGN KEY (atendente_id) REFERENCES atendentes (id),
    CONSTRAINT chk_atendimento_assunto
        CHECK (assunto IN ('PROBLEMA_CARTAO', 'CONTRATACAO_EMPRESTIMO', 'OUTROS')),
    CONSTRAINT chk_atendimento_time
        CHECK (time_atendimento IN ('CARTOES', 'EMPRESTIMOS', 'OUTROS_ASSUNTOS')),
    CONSTRAINT chk_atendimento_status
        CHECK (status IN ('AGUARDANDO', 'EM_ATENDIMENTO', 'FINALIZADO'))
);

CREATE INDEX IF NOT EXISTS idx_atendimento_status_time
    ON atendimentos (status, time_atendimento);

CREATE INDEX IF NOT EXISTS idx_atendimento_time_status_criado
    ON atendimentos (time_atendimento, status, criado_em);

CREATE INDEX IF NOT EXISTS idx_atendimento_atendente_status
    ON atendimentos (atendente_id, status);
